# Run: python .\manage.py india_location
from django.core.management.base import BaseCommand
from django.db import IntegrityError
from location.models import Country, State, District, City


class Command(BaseCommand):
    help = ""

    def handle(self, *args, **options):

        countries = {
            "Afghanistan",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegovina",
            "Botswana",
            "Brazil",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cabo Verde",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Colombia",
            "Comoros",
            "Congo",
            "Costa Rica",
            "Croatia",
            "Cuba",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "East Timor",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Eswatini",
            "Ethiopia",
            "Fiji",
            "Finland",
            "France",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Greece",
            "Grenada",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Israel",
            "Italy",
            "Ivory Coast",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Korea, North",
            "Korea, South",
            "Kosovo",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Mauritania",
            "Mauritius",
            "Mexico",
            "Micronesia",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Morocco",
            "Mozambique",
            "Myanmar",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "North Macedonia",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Palestine",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Qatar",
            "Romania",
            "Russia",
            "Rwanda",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Togo",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom",
            "United States",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Vatican City",
            "Venezuela",
            "Vietnam",
            "Yemen",
            "Zambia",
            "Zimbabwe",
        }
        state = {
            "India": [
                "Andhra Pradesh",
                "Arunachal Pradesh",
                "Assam",
                "Bihar",
                "Chhattisgarh",
                "Goa",
                "Gujarat",
                "Haryana",
                "Himachal Pradesh",
                "Jharkhand",
                "Karnataka",
                "Kerala",
                "Madhya Pradesh",
                "Maharashtra",
                "Manipur",
                "Meghalaya",
                "Mizoram",
                "Nagaland",
                "Odisha",
                "Punjab",
                "Rajasthan",
                "Sikkim",
                "Tamil Nadu",
                "Telangana",
                "Tripura",
                "Uttar Pradesh",
                "Uttarakhand",
                "West Bengal",
                "Andaman and Nicobar Islands",
                "Chandigarh",
                "Dadra and Nagar Haveli and Daman and Diu",
                "Delhi",
                "Lakshadweep",
                "Puducherry",
            ],
            "Germany": [
                "Baden-Württemberg",
                "Bavaria",
                "Berlin",
                "Brandenburg",
                "Bremen",
                "Hamburg",
                "Hesse",
                "Lower Saxony",
                "Mecklenburg-Vorpommern",
                "North Rhine-Westphalia",
                "Rhineland-Palatinate",
                "Saarland",
                "Saxony",
                "Saxony-Anhalt",
                "Schleswig-Holstein",
                "Thuringia",
            ],
            "Iran": [
                "Alborz",
                "Ardabil",
                "East Azerbaijan",
                "West Azerbaijan",
                "Bushehr",
                "Chaharmahal and Bakhtiari",
                "Fars",
                "Gilan",
                "Golestan",
                "Hormozgan",
                "Ilam",
                "Isfahan",
                "Kerman",
                "Kermanshah",
                "North Khorasan",
                "Razavi Khorasan",
                "South Khorasan",
                "Khuzestan",
                "Kohgiluyeh and Boyer-Ahmad",
                "Kurdistan",
                "Lorestan",
                "Markazi",
                "Mazandaran",
                "Qazvin",
                "Qom",
                "Semnan",
                "Sistan and Baluchestan",
                "Tehran",
                "Yazd",
                "Zanjan",
            ],
        }
        districts = {
            "Andhra Pradesh": [
                "Anantapur",
                "Chittoor",
                "East Godavari",
                "Guntur",
                "Kadapa",
                "Krishna",
                "Kurnool",
                "Nellore",
                "Prakasam",
                "Srikakulam",
                "Visakhapatnam",
                "Vizianagaram",
                "West Godavari",
            ],
            "Arunachal Pradesh": [
                "Anjaw",
                "Changlang",
                "Dibang Valley",
                "East Kameng",
                "East Siang",
                "Kamle",
                "Kra Daadi",
                "Kurung Kumey",
                "Lepa Rada",
                "Lohit",
                "Longding",
                "Lower Dibang Valley",
                "Lower Siang",
                "Lower Subansiri",
                "Namsai",
                "Pakke Kessang",
                "Papum Pare",
                "Shi Yomi",
                "Siang",
                "Tawang",
                "Tirap",
                "Upper Siang",
                "Upper Subansiri",
                "West Kameng",
                "West Siang",
            ],
            "Assam": [
                "Baksa",
                "Barpeta",
                "Biswanath",
                "Bongaigaon",
                "Cachar",
                "Charaideo",
                "Chirang",
                "Darrang",
                "Dhemaji",
                "Dhubri",
                "Dibrugarh",
                "Dima Hasao",
                "Goalpara",
                "Golaghat",
                "Hailakandi",
                "Hojai",
                "Jorhat",
                "Kamrup",
                "Kamrup Metropolitan",
                "Karbi Anglong",
                "Karimganj",
                "Kokrajhar",
                "Lakhimpur",
                "Majuli",
                "Morigaon",
                "Nagaon",
                "Nalbari",
                "Sivasagar",
                "Sonitpur",
                "South Salmara-Mankachar",
                "Tinsukia",
                "Udalguri",
                "West Karbi Anglong",
            ],
            "Bihar": [
                "Araria",
                "Arwal",
                "Aurangabad",
                "Banka",
                "Begusarai",
                "Bhagalpur",
                "Bhojpur",
                "Buxar",
                "Darbhanga",
                "East Champaran",
                "Gaya",
                "Gopalganj",
                "Jamui",
                "Jehanabad",
                "Kaimur",
                "Katihar",
                "Khagaria",
                "Kishanganj",
                "Lakhisarai",
                "Madhepura",
                "Madhubani",
                "Munger",
                "Muzaffarpur",
                "Nalanda",
                "Nawada",
                "Patna",
                "Purnia",
                "Rohtas",
                "Saharsa",
                "Samastipur",
                "Saran",
                "Sheikhpura",
                "Sheohar",
                "Sitamarhi",
                "Siwan",
                "Supaul",
                "Vaishali",
                "West Champaran",
            ],
            "Chhattisgarh": [
                "Balod",
                "Baloda Bazar",
                "Balrampur",
                "Bastar",
                "Bemetara",
                "Bijapur",
                "Bilaspur",
                "Dantewada",
                "Dhamtari",
                "Durg",
                "Gariaband",
                "Gaurela-Pendra-Marwahi",
                "Janjgir-Champa",
                "Jashpur",
                "Kanker",
                "Kawardha",
                "Kondagaon",
                "Korba",
                "Koriya",
                "Mahasamund",
                "Mungeli",
                "Narayanpur",
                "Raigarh",
                "Raipur",
                "Rajnandgaon",
                "Sukma",
                "Surajpur",
                "Surguja",
            ],
            "Goa": ["North Goa", "South Goa"],
            "Gujarat": [
                "Ahmedabad",
                "Amreli",
                "Anand",
                "Aravalli",
                "Banaskantha",
                "Bharuch",
                "Bhavnagar",
                "Botad",
                "Chhota Udaipur",
                "Dahod",
                "Dang",
                "Devbhoomi Dwarka",
                "Gandhinagar",
                "Gir Somnath",
                "Jamnagar",
                "Junagadh",
                "Kheda",
                "Kutch",
                "Mahisagar",
                "Mehsana",
                "Morbi",
                "Narmada",
                "Navsari",
                "Panchmahal",
                "Patan",
                "Porbandar",
                "Rajkot",
                "Sabarkantha",
                "Surat",
                "Surendranagar",
                "Tapi",
                "Vadodara",
                "Valsad",
            ],
            "Haryana": [
                "Ambala",
                "Bhiwani",
                "Charkhi Dadri",
                "Faridabad",
                "Fatehabad",
                "Gurugram",
                "Hisar",
                "Jhajjar",
                "Jind",
                "Kaithal",
                "Karnal",
                "Kurukshetra",
                "Mahendragarh",
                "Nuh",
                "Palwal",
                "Panchkula",
                "Panipat",
                "Rewari",
                "Rohtak",
                "Sirsa",
                "Sonipat",
                "Yamunanagar",
            ],
            "Himachal Pradesh": [
                "Bilaspur",
                "Chamba",
                "Hamirpur",
                "Kangra",
                "Kinnaur",
                "Kullu",
                "Lahaul and Spiti",
                "Mandi",
                "Shimla",
                "Sirmaur",
                "Solan",
                "Una",
            ],
            "Jharkhand": [
                "Bokaro",
                "Chatra",
                "Deoghar",
                "Dhanbad",
                "Dumka",
                "East Singhbhum",
                "Garhwa",
                "Giridih",
                "Godda",
                "Gumla",
                "Hazaribagh",
                "Jamtara",
                "Khunti",
                "Koderma",
                "Latehar",
                "Lohardaga",
                "Pakur",
                "Palamu",
                "Ramgarh",
                "Ranchi",
                "Sahibganj",
                "Seraikela Kharsawan",
                "Simdega",
                "West Singhbhum",
            ],
            "Karnataka": [
                "Bagalkot",
                "Ballari",
                "Belagavi",
                "Bengaluru Rural",
                "Bengaluru Urban",
                "Bidar",
                "Chamarajanagar",
                "Chikkaballapur",
                "Chikkamagaluru",
                "Chitradurga",
                "Dakshina Kannada",
                "Davanagere",
                "Dharwad",
                "Gadag",
                "Hassan",
                "Haveri",
                "Kalaburagi",
                "Kodagu",
                "Kolar",
                "Koppal",
                "Mandya",
                "Mysuru",
                "Raichur",
                "Ramanagara",
                "Shivamogga",
                "Tumakuru",
                "Udupi",
                "Uttara Kannada",
                "Vijayapura",
                "Yadgir",
            ],
            "Kerala": [
                "Alappuzha",
                "Ernakulam",
                "Idukki",
                "Kannur",
                "Kasaragod",
                "Kollam",
                "Kottayam",
                "Kozhikode",
                "Malappuram",
                "Palakkad",
                "Pathanamthitta",
                "Thiruvananthapuram",
                "Thrissur",
                "Wayanad",
            ],
            "Madhya Pradesh": [
                "Agar Malwa",
                "Alirajpur",
                "Anuppur",
                "Ashoknagar",
                "Balaghat",
                "Barwani",
                "Betul",
                "Bhind",
                "Bhopal",
                "Burhanpur",
                "Chhatarpur",
                "Chhindwara",
                "Damoh",
                "Datia",
                "Dewas",
                "Dhar",
                "Dindori",
                "Guna",
                "Gwalior",
                "Harda",
                "Hoshangabad",
                "Indore",
                "Jabalpur",
                "Jhabua",
                "Katni",
                "Khandwa",
                "Khargone",
                "Mandla",
                "Mandsaur",
                "Morena",
                "Narsinghpur",
                "Neemuch",
                "Panna",
                "Raisen",
                "Rajgarh",
                "Ratlam",
                "Rewa",
                "Sagar",
                "Satna",
                "Sehore",
                "Seoni",
                "Shahdol",
                "Shajapur",
                "Sheopur",
                "Shivpuri",
                "Sidhi",
                "Singrauli",
                "Tikamgarh",
                "Ujjain",
                "Umaria",
                "Vidisha",
            ],
            "Maharashtra": [
                "Ahmednagar",
                "Akola",
                "Amravati",
                "Aurangabad",
                "Beed",
                "Bhandara",
                "Buldhana",
                "Chandrapur",
                "Dhule",
                "Gadchiroli",
                "Gondia",
                "Hingoli",
                "Jalgaon",
                "Jalna",
                "Kolhapur",
                "Latur",
                "Mumbai City",
                "Mumbai Suburban",
                "Nagpur",
                "Nanded",
                "Nandurbar",
                "Nashik",
                "Osmanabad",
                "Palghar",
                "Parbhani",
                "Pune",
                "Raigad",
                "Ratnagiri",
                "Sangli",
                "Satara",
                "Sindhudurg",
                "Solapur",
                "Thane",
                "Wardha",
                "Washim",
                "Yavatmal",
            ],
            "Manipur": [
                "Bishnupur",
                "Chandel",
                "Churachandpur",
                "Imphal East",
                "Imphal West",
                "Jiribam",
                "Kakching",
                "Kamjong",
                "Kangpokpi",
                "Noney",
                "Pherzawl",
                "Senapati",
                "Tamenglong",
                "Tengnoupal",
                "Thoubal",
                "Ukhrul",
            ],
            "Meghalaya": [
                "East Garo Hills",
                "East Jaintia Hills",
                "East Khasi Hills",
                "North Garo Hills",
                "Ri-Bhoi",
                "South Garo Hills",
                "South West Garo Hills",
                "South West Khasi Hills",
                "West Garo Hills",
                "West Jaintia Hills",
                "West Khasi Hills",
            ],
            "Mizoram": [
                "Aizawl",
                "Champhai",
                "Hnahthial",
                "Khawzawl",
                "Kolasib",
                "Lawngtlai",
                "Lunglei",
                "Mamit",
                "Saiha",
                "Saitual",
                "Serchhip",
            ],
            "Nagaland": [
                "Dimapur",
                "Kiphire",
                "Kohima",
                "Longleng",
                "Mokokchung",
                "Mon",
                "Peren",
                "Phek",
                "Tuensang",
                "Wokha",
                "Zunheboto",
            ],
            "Odisha": [
                "Angul",
                "Balangir",
                "Balasore",
                "Bargarh",
                "Bhadrak",
                "Boudh",
                "Cuttack",
                "Deogarh",
                "Dhenkanal",
                "Gajapati",
                "Ganjam",
                "Jagatsinghpur",
                "Jajpur",
                "Jharsuguda",
                "Kalahandi",
                "Kandhamal",
                "Kendrapara",
                "Kendujhar",
                "Khordha",
                "Koraput",
                "Malkangiri",
                "Mayurbhanj",
                "Nabarangpur",
                "Nayagarh",
                "Nuapada",
                "Puri",
                "Rayagada",
                "Sambalpur",
                "Subarnapur",
                "Sundargarh",
            ],
            "Punjab": [
                "Amritsar",
                "Barnala",
                "Bathinda",
                "Faridkot",
                "Fatehgarh Sahib",
                "Fazilka",
                "Ferozepur",
                "Gurdaspur",
                "Hoshiarpur",
                "Jalandhar",
                "Kapurthala",
                "Ludhiana",
                "Mansa",
                "Moga",
                "Muktsar",
                "Pathankot",
                "Patiala",
                "Rupnagar",
                "Sangrur",
                "Shaheed Bhagat Singh Nagar",
                "Sri Muktsar Sahib",
                "Tarn Taran",
            ],
            "Rajasthan": [
                "Ajmer",
                "Alwar",
                "Banswara",
                "Baran",
                "Barmer",
                "Bharatpur",
                "Bhilwara",
                "Bikaner",
                "Bundi",
                "Chittorgarh",
                "Churu",
                "Dausa",
                "Dholpur",
                "Dungarpur",
                "Hanumangarh",
                "Jaipur",
                "Jaisalmer",
                "Jalore",
                "Jhalawar",
                "Jhunjhunu",
                "Jodhpur",
                "Karauli",
                "Kota",
                "Nagaur",
                "Pali",
                "Pratapgarh",
                "Rajsamand",
                "Sawai Madhopur",
                "Sikar",
                "Sirohi",
                "Sri Ganganagar",
                "Tonk",
                "Udaipur",
            ],
            "Sikkim": ["East Sikkim", "North Sikkim", "South Sikkim", "West Sikkim"],
            "Tamil Nadu": [
                "Ariyalur",
                "Chengalpattu",
                "Chennai",
                "Coimbatore",
                "Cuddalore",
                "Dharmapuri",
                "Dindigul",
                "Erode",
                "Kallakurichi",
                "Kanchipuram",
                "Kanyakumari",
                "Karur",
                "Krishnagiri",
                "Madurai",
                "Mayiladuthurai",
                "Nagapattinam",
                "Namakkal",
                "Nilgiris",
                "Perambalur",
                "Pudukkottai",
                "Ramanathapuram",
                "Ranipet",
                "Salem",
                "Sivaganga",
                "Tenkasi",
                "Thanjavur",
                "Theni",
                "Thoothukudi",
                "Tiruchirappalli",
                "Tirunelveli",
                "Tirupathur",
                "Tiruppur",
                "Tiruvallur",
                "Tiruvannamalai",
                "Tiruvarur",
                "Vellore",
                "Viluppuram",
                "Virudhunagar",
            ],
            "Telangana": [
                "Adilabad",
                "Bhadradri Kothagudem",
                "Hyderabad",
                "Jagtial",
                "Jangaon",
                "Jayashankar Bhupalapally",
                "Jogulamba Gadwal",
                "Kamareddy",
                "Karimnagar",
                "Khammam",
                "Kumuram Bheem",
                "Mahabubabad",
                "Mahabubnagar",
                "Mancherial",
                "Medak",
                "Medchal–Malkajgiri",
                "Mulugu",
                "Nagarkurnool",
                "Nalgonda",
                "Narayanpet",
                "Nirmal",
                "Nizamabad",
                "Peddapalli",
                "Rajanna Sircilla",
                "Rangareddy",
                "Sangareddy",
                "Siddipet",
                "Suryapet",
                "Vikarabad",
                "Wanaparthy",
                "Warangal Rural",
                "Warangal Urban",
                "Yadadri Bhuvanagiri",
            ],
            "Tripura": [
                "Dhalai",
                "Gomati",
                "Khowai",
                "North Tripura",
                "Sepahijala",
                "South Tripura",
                "Unakoti",
                "West Tripura",
            ],
            "Uttar Pradesh": [
                "Agra",
                "Aligarh",
                "Ambedkar Nagar",
                "Amethi",
                "Amroha",
                "Auraiya",
                "Ayodhya",
                "Azamgarh",
                "Baghpat",
                "Bahraich",
                "Ballia",
                "Balrampur",
                "Banda",
                "Barabanki",
                "Bareilly",
                "Basti",
                "Bhadohi",
                "Bijnor",
                "Budaun",
                "Bulandshahr",
                "Chandauli",
                "Chitrakoot",
                "Deoria",
                "Etah",
                "Etawah",
                "Farrukhabad",
                "Fatehpur",
                "Firozabad",
                "Gautam Buddha Nagar",
                "Ghaziabad",
                "Ghazipur",
                "Gonda",
                "Gorakhpur",
                "Hamirpur",
                "Hapur",
                "Hardoi",
                "Hathras",
                "Jalaun",
                "Jaunpur",
                "Jhansi",
                "Kannauj",
                "Kanpur Dehat",
                "Kanpur Nagar",
                "Kasganj",
                "Kaushambi",
                "Kheri",
                "Kushinagar",
                "Lalitpur",
                "Lucknow",
                "Maharajganj",
                "Mahoba",
                "Mainpuri",
                "Mathura",
                "Mau",
                "Meerut",
                "Mirzapur",
                "Moradabad",
                "Muzaffarnagar",
                "Pilibhit",
                "Pratapgarh",
                "Prayagraj",
                "Raebareli",
                "Rampur",
                "Saharanpur",
                "Sambhal",
                "Sant Kabir Nagar",
                "Shahjahanpur",
                "Shamli",
                "Shrawasti",
                "Siddharthnagar",
                "Sitapur",
                "Sonbhadra",
                "Sultanpur",
                "Unnao",
                "Varanasi",
            ],
            "Uttarakhand": [
                "Almora",
                "Bageshwar",
                "Chamoli",
                "Champawat",
                "Dehradun",
                "Haridwar",
                "Nainital",
                "Pauri Garhwal",
                "Pithoragarh",
                "Rudraprayag",
                "Tehri Garhwal",
                "Udham Singh Nagar",
                "Uttarkashi",
            ],
            "West Bengal": [
                "Alipurduar",
                "Bankura",
                "Birbhum",
                "Cooch Behar",
                "Dakshin Dinajpur",
                "Darjeeling",
                "Hooghly",
                "Howrah",
                "Jalpaiguri",
                "Jhargram",
                "Kalimpong",
                "Kolkata",
                "Malda",
                "Murshidabad",
                "Nadia",
                "North 24 Parganas",
                "Paschim Bardhaman",
                "Paschim Medinipur",
                "Purba Bardhaman",
                "Purba Medinipur",
                "Purulia",
                "South 24 Parganas",
                "Uttar Dinajpur",
            ],
            "Baden-Württemberg": [
                "Karlsruhe",
                "Heidelberg",
                "Mannheim",
                "Stuttgart",
                "Freiburg",
                "Tübingen",
                "Freudenstadt",
                "Heilbronn",
                "Hohenlohekreis",
                "Main-Tauber-Kreis",
                "Neckar-Odenwald-Kreis",
                "Rastatt",
                "Heidenheim",
                "Ostalbkreis",
                "Alb-Donau-Kreis",
                "Biberach",
                "Bodenseekreis",
                "Ravensburg",
                "Sigmaringen",
                "Rems-Murr-Kreis",
                "Göppingen",
                "Ludwigsburg",
                "Böblingen",
                "Esslingen",
                "Reutlingen",
                "Calw",
                "Enzkreis",
                "Karlsruhe",
                "Ortenaukreis",
                "Rottweil",
                "Schwarzwald-Baar-Kreis",
                "Tuttlingen",
                "Konstanz",
                "Lörrach",
                "Waldshut",
            ],
            "Bavaria": [
                "Altötting",
                "Berchtesgadener Land",
                "Bad Kissingen",
                "Deggendorf",
                "Dachau",
                "Ebersberg",
                "Erding",
                "Freyung-Grafenau",
                "Fürstenfeldbruck",
                "Garmisch-Partenkirchen",
                "Landsberg am Lech",
                "Mühldorf am Inn",
                "Miesbach",
                "Neustadt an der Waldnaab",
                "Neuburg-Schrobenhausen",
                "Rosenheim",
                "Regen",
                "Straubing-Bogen",
                "Starnberg",
                "Tirschenreuth",
                "Weilheim-Schongau",
                "Würzburg",
                "Aschaffenburg",
                "Bad Tölz-Wolfratshausen",
                "Cham",
                "Dingolfing-Landau",
                "Kelheim",
                "Lindau",
                "Landshut",
                "Miltenberg",
                "Pfaffenhofen an der Ilm",
                "Regensburg",
                "Rottal-Inn",
                "Schwandorf",
                "Schweinfurt",
                "Tutzing",
                "Amberg",
                "Bayreuth",
                "Coburg",
                "Erlangen",
                "Hof",
                "Ingolstadt",
                "Kempten",
                "Memmingen",
                "Nuremberg",
                "Passau",
                "Schweinfurt",
                "Straubing",
                "Weiden",
                "Würzburg",
            ],
            "Berlin": ["Berlin"],
            "Brandenburg": [
                "Barnim",
                "Dahme-Spreewald",
                "Elbe-Elster",
                "Havelland",
                "Märkisch-Oderland",
                "Oberhavel",
                "Oberspreewald-Lausitz",
                "Oder-Spree",
                "Ostprignitz-Ruppin",
                "Potsdam-Mittelmark",
                "Prignitz",
                "Spree-Neiße",
                "Teltow-Fläming",
                "Uckermark",
            ],
            "Bremen": ["Bremen", "Bremerhaven"],
            "Hamburg": ["Hamburg"],
            "Hesse": [
                "Bergstraße",
                "Darmstadt",
                "Frankfurt am Main",
                "Fulda",
                "Gießen",
                "Groß-Gerau",
                "Hersfeld-Rotenburg",
                "Hochtaunuskreis",
                "Kassel",
                "Lahn-Dill-Kreis",
                "Limburg-Weilburg",
                "Main-Kinzig-Kreis",
                "Main-Taunus-Kreis",
                "Marburg-Biedenkopf",
                "Odenwaldkreis",
                "Offenbach",
                "Rheingau-Taunus-Kreis",
                "Schwalm-Eder-Kreis",
                "Vogelsbergkreis",
                "Waldeck-Frankenberg",
                "Werra-Meißner-Kreis",
                "Wetteraukreis",
            ],
            "Lower Saxony": [
                "Ammerland",
                "Aurich",
                "Braunschweig",
                "Celle",
                "Cloppenburg",
                "Cuxhaven",
                "Diepholz",
                "Emden",
                "Emsland",
                "Friesland",
                "Gifhorn",
                "Goslar",
                "Göttingen",
                "Hameln-Pyrmont",
                "Hannover",
                "Harburg",
                "Heidekreis",
                "Helmstedt",
                "Hildesheim",
                "Holzminden",
                "Leer",
                "Lüchow-Dannenberg",
                "Lüneburg",
                "Nienburg/Weser",
                "Northeim",
                "Oldenburg",
                "Osnabrück",
                "Osterholz",
                "Peine",
                "Rotenburg (Wümme)",
                "Salzgitter",
                "Schaumburg",
                "Stade",
                "Uelzen",
                "Vechta",
                "Verden",
                "Wesermarsch",
                "Wilhelmshaven",
                "Wittmund",
                "Wolfenbüttel",
                "Wolfsburg",
            ],
            "Mecklenburg-Vorpommern": [
                "Mecklenburgische Seenplatte",
                "Rostock",
                "Schwerin",
                "Vorpommern-Greifswald",
                "Vorpommern-Rügen",
            ],
            "North Rhine-Westphalia": [
                "Aachen",
                "Bielefeld",
                "Bochum",
                "Bonn",
                "Borken",
                "Bottrop",
                "Coesfeld",
                "Dortmund",
                "Duisburg",
                "Düren",
                "Düsseldorf",
                "Ennepe-Ruhr-Kreis",
                "Essen",
                "Euskirchen",
                "Gelsenkirchen",
                "Gütersloh",
                "Hagen",
                "Hamm",
                "Heinsberg",
                "Herford",
                "Herne",
                "Hochsauerlandkreis",
                "Höxter",
                "Kleve",
                "Cologne",
                "Leverkusen",
                "Lippe",
                "Märkischer Kreis",
                "Mettmann",
                "Minden-Lübbecke",
                "Mönchengladbach",
                "Mülheim an der Ruhr",
                "Münster",
                "Oberbergischer Kreis",
                "Oberhausen",
                "Olpe",
                "Paderborn",
                "Recklinghausen",
                "Remscheid",
                "Rhein-Erft-Kreis",
                "Rhein-Kreis Neuss",
                "Rheinisch-Bergischer Kreis",
                "Siegen-Wittgenstein",
                "Soest",
                "Solingen",
                "Städteregion Aachen",
                "Steinfurt",
                "Unna",
                "Viersen",
                "Warendorf",
                "Wesel",
            ],
            "Rhineland-Palatinate": [
                "Ahrweiler",
                "Altenkirchen",
                "Alzey-Worms",
                "Bad Dürkheim",
                "Bad Kreuznach",
                "Bernkastel-Wittlich",
                "Birkenfeld",
                "Bitburg-Prüm",
                "Cochem-Zell",
                "Donnersbergkreis",
                "Frankenthal",
                "Germersheim",
                "Kaiserslautern",
                "Koblenz",
                "Kusel",
                "Landau",
                "Ludwigshafen",
                "Mainz",
                "Mainz-Bingen",
                "Mayen-Koblenz",
                "Neustadt an der Weinstraße",
                "Neuwied",
                "Pirmasens",
                "Rhein-Hunsrück-Kreis",
                "Rhein-Lahn-Kreis",
                "Rhein-Pfalz-Kreis",
                "Speyer",
                "Südliche Weinstraße",
                "Trier",
                "Trier-Saarburg",
                "Westerwaldkreis",
                "Worms",
                "Zweibrücken",
            ],
            "Saarland": [
                "Merzig-Wadern",
                "Neunkirchen",
                "Saarbrücken",
                "Saarlouis",
                "Saarpfalz-Kreis",
                "Sankt Wendel",
            ],
            "Saxony": [
                "Bautzen",
                "Chemnitz",
                "Dresden",
                "Erzgebirgskreis",
                "Görlitz",
                "Leipzig",
                "Meißen",
                "Mittelsachsen",
                "Nordsachsen",
                "Sächsische Schweiz-Osterzgebirge",
                "Vogtlandkreis",
                "Zwickau",
            ],
            "Saxony-Anhalt": [
                "Altmarkkreis Salzwedel",
                "Anhalt-Bitterfeld",
                "Börde",
                "Burgenlandkreis",
                "Dessau-Roßlau",
                "Halle",
                "Harz",
                "Jerichower Land",
                "Magdeburg",
                "Mansfeld-Südharz",
                "Saalekreis",
                "Salzlandkreis",
                "Stendal",
                "Wittenberg",
            ],
            "Schleswig-Holstein": [
                "Dithmarschen",
                "Herzogtum Lauenburg",
                "Kiel",
                "Lübeck",
                "Neumünster",
                "Nordfriesland",
                "Ostholstein",
                "Pinneberg",
                "Plön",
                "Rendsburg-Eckernförde",
                "Schleswig-Flensburg",
                "Segeberg",
                "Steinburg",
                "Stormarn",
            ],
            "Thuringia": [
                "Altenburger Land",
                "Eichsfeld",
                "Eisenach",
                "Erfurt",
                "Gera",
                "Gotha",
                "Greiz",
                "Hildburghausen",
                "Ilm-Kreis",
                "Jena",
                "Kyffhäuserkreis",
                "Nordhausen",
                "Saale-Holzland-Kreis",
                "Saale-Orla-Kreis",
                "Saalfeld-Rudolstadt",
                "Schmalkalden-Meiningen",
                "Sömmerda",
                "Sonneberg",
                "Unstrut-Hainich-Kreis",
                "Wartburgkreis",
                "Weimar",
                "Weimarer Land",
            ],
        }
        city = {
            "Aachen": ["Aachen", "Herzogenrath", "Würselen", "Stolberg (Rhineland)"],
            "Augsburg": ["Augsburg", "Friedberg", "Gersthofen", "Neusäß"],
            "Berlin": ["Berlin"],
            "Bielefeld": ["Bielefeld"],
            "Bochum": ["Bochum", "Herne", "Witten", "Hattingen"],
            "Bonn": ["Bonn", "Bad Godesberg", "Beuel"],
            "Bremen": ["Bremen"],
            "Bremerhaven": ["Bremerhaven"],
            "Chemnitz": ["Chemnitz"],
            "Cologne": ["Cologne", "Bonn", "Leverkusen", "Bergisch Gladbach"],
            "Darmstadt": ["Darmstadt", "Frankfurt"],
            "Dortmund": ["Dortmund", "Lünen", "Castrop-Rauxel", "Hagen"],
            "Dresden": ["Dresden"],
            "Duisburg": ["Duisburg", "Mülheim", "Essen", "Dinslaken"],
            "Düsseldorf": ["Düsseldorf", "Duisburg", "Mönchengladbach", "Krefeld"],
            "Erfurt": ["Erfurt"],
            "Erlangen": ["Erlangen"],
            "Essen": ["Essen", "Gelsenkirchen", "Bottrop", "Velbert"],
            "Frankfurt": ["Frankfurt", "Offenbach", "Darmstadt", "Hanau"],
            "Freiburg im Breisgau": ["Freiburg im Breisgau"],
            "Fürth": ["Fürth"],
            "Gelsenkirchen": ["Gelsenkirchen"],
            "Gera": ["Gera"],
            "Göttingen": ["Göttingen"],
            "Hagen": ["Hagen"],
            "Halle (Saale)": ["Halle (Saale)"],
            "Hamburg": ["Hamburg"],
            "Hamm": ["Hamm"],
            "Hanover": ["Hanover", "Hildesheim", "Langenhagen", "Garbsen"],
            "Heidelberg": ["Heidelberg"],
            "Heilbronn": ["Heilbronn"],
            "Herne": ["Herne"],
            "Ingolstadt": ["Ingolstadt"],
            "Jena": ["Jena"],
            "Karlsruhe": ["Karlsruhe"],
            "Kassel": ["Kassel"],
            "Kiel": ["Kiel"],
            "Krefeld": ["Krefeld"],
            "Leipzig": ["Leipzig"],
            "Leverkusen": ["Leverkusen"],
            "Ludwigshafen am Rhein": ["Ludwigshafen am Rhein"],
            "Lübeck": ["Lübeck"],
            "Magdeburg": ["Magdeburg"],
            "Mainz": ["Mainz"],
            "Mannheim": ["Mannheim"],
            "Mönchengladbach": ["Mönchengladbach"],
            "Munich": ["Munich"],
            "Münster": ["Münster"],
            "Nuremberg": ["Nuremberg"],
            "Oberhausen": ["Oberhausen"],
            "Oldenburg": ["Oldenburg"],
            "Osnabrück": ["Osnabrück"],
            "Paderborn": ["Paderborn"],
            "Potsdam": ["Potsdam"],
            "Recklinghausen": ["Recklinghausen"],
            "Regensburg": ["Regensburg"],
            "Remscheid": ["Remscheid"],
            "Reutlingen": ["Reutlingen"],
            "Rostock": ["Rostock"],
            "Saarbrücken": ["Saarbrücken"],
            "Salzgitter": ["Salzgitter"],
            "Siegen": ["Siegen"],
            "Solingen": ["Solingen"],
            "Stuttgart": ["Stuttgart"],
            "Trier": ["Trier"],
            "Ulm": ["Ulm"],
            "Wiesbaden": ["Wiesbaden"],
            "Wolfsburg": ["Wolfsburg"],
            "Wuppertal": ["Wuppertal"],
            "Würzburg": ["Würzburg"],
            "Anantapur": ["Anantapur", "Guntakal", "Dharmavaram", "Hindupur"],
            "Chittoor": ["Tirupati", "Chittoor", "Srikalahasti", "Madanapalle"],
            "East Godavari": ["Kakinada", "Rajahmundry", "Amalapuram", "Mandapeta"],
            "Guntur": ["Guntur", "Tenali", "Narasaraopet", "Macherla"],
            "Krishna": ["Vijayawada", "Machilipatnam", "Gannavaram", "Nuzvid"],
            "Kurnool": ["Kurnool", "Adoni", "Nandyal", "Yemmiganur"],
            "Prakasam": ["Ongole", "Chirala", "Kandukur", "Markapur"],
            "Srikakulam": ["Srikakulam", "Tekkali", "Palasa", "Narasannapeta"],
            "Visakhapatnam": ["Visakhapatnam", "Vizianagaram", "Anakapalle", "Paderu"],
            "Vizianagaram": ["Vizianagaram", "Bobbili", "Salur", "Parvathipuram"],
            "West Godavari": ["Eluru", "Tadepalligudem", "Bhimavaram", "Narsapur"],
            "Y.S.R. Kadapa": ["Kadapa", "Proddatur", "Rayachoti", "Jammalamadugu"],
            "Anjaw": ["Hayuliang", "Chaglagam", "Hawai", "Kibithoo"],
            "Changlang": ["Changlang", "Kharsang", "Miao", "Nampong"],
            "Dibang Valley": ["Anini", "Roing", "Tezu", "Hunli"],
            "East Kameng": ["Seppa", "Chayangtajo", "Bameng", "Lada"],
            "East Siang": ["Pasighat", "Mebo", "Nari-Koyu", "Ruksin"],
            "Kamle": ["Raga", "Tamen-Raga", "Pania", "Damin"],
            "Kra Daadi": ["Jamin", "Pania", "Damin", "Jamin"],
            "Kurung Kumey": ["Koloriang", "Palin", "Nyapin", "Tali"],
            "Lepa Rada": ["Basar", "Likabali", "Tirbin", "Tato"],
            "Lohit": ["Tezu", "Chowkham", "Wakro", "Namsai"],
            "Longding": ["Longding", "Pumao", "Pongchau", "Kanubari"],
            "Lower Dibang Valley": ["Roing", "Hunli", "Anini", "Iphi"],
            "Lower Siang": ["Yingkiong", "Tuting", "Geku", "Mariyang"],
            "Lower Subansiri": ["Ziro", "Raga", "Yazali", "Talo"],
            "Namsai": ["Namsai", "Chongkham", "Lathao", "Mahadevpur"],
            "Pakke Kessang": ["Lemmi", "Khenewa", "Seijosa", "Pakke-Kessang"],
            "Papum Pare": ["Itanagar", "Naharlagun", "Yupia", "Banderdewa"],
            "Shi Yomi": ["Mechuka", "Tato", "Pidi", "Tato"],
            "Siang": ["Boleng", "Kaying", "Pangin", "Rumgong"],
            "Tawang": ["Tawang", "Jang", "Lumla", "Zemithang"],
            "Tirap": ["Khonsa", "Deomali", "Kanubari", "Borduria"],
            "Upper Siang": ["Yingkiong", "Tuting", "Geku", "Mariyang"],
            "Upper Subansiri": ["Daporijo", "Dumporijo", "Taliha", "Maro"],
            "West Kameng": ["Bomdila", "Dirang", "Rupa", "Kalaktang"],
            "West Siang": ["Aalo", "Along", "Likabali", "Basa"],
        }

        # Country Writer
        for country_name in countries:
            try:
                country = Country.objects.create(name=country_name)
                self.stdout.write(
                    self.style.SUCCESS(f"Successfully created Country: {country_name}")
                )
            except:
                self.stdout.write(
                    self.style.ERROR(
                        f"Failed to create Country (already exists): {country_name}. Skipping..."
                    )
                )

        # State Writer
        for country_name, states in state.items():
            country = Country.objects.get(name=country_name)
            for state_name in states:
                try:
                    state = State.objects.create(name=state_name, country=country)
                    self.stdout.write(
                        self.style.SUCCESS(f"Successfully created State: {state_name}")
                    )
                except IntegrityError:
                    self.stdout.write(
                        self.style.ERROR(
                            f"Failed to create State (already exists): {state_name}. Skipping..."
                        )
                    )

        # District Writer
        for state_name, districts in districts.items():
            state = State.objects.get(name=state_name)
            for district_name in districts:
                try:
                    district = District.objects.create(name=district_name, state=state)
                    self.stdout.write(
                        self.style.SUCCESS(
                            f"Successfully created District: {district_name}"
                        )
                    )
                except IntegrityError:
                    self.stdout.write(
                        self.style.ERROR(
                            f"Failed to create District (already exists): {district_name}. Skipping..."
                        )
                    )

        # City Writer
        for district_name, cities in city.items():
            try:
                district = District.objects.get(name=district_name)
            except District.DoesNotExist:
                f"Failed to Find District (already exists): {district_name}. Skipping..."
                continue

            for city_name in cities:
                try:
                    city = City.objects.create(name=city_name, district=district)
                    self.stdout.write(
                        self.style.SUCCESS(f"Successfully created City: {city_name}")
                    )
                except IntegrityError:
                    self.stdout.write(
                        self.style.ERROR(
                            f"Failed to create City (already exists): {city_name}. Skipping..."
                        )
                    )
