# Generated by Django 5.0.2 on 2024-03-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_image_productphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphoto',
            name='photo',
        ),
        migrations.AddField(
            model_name='productphoto',
            name='fifth_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='first_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='fourth_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='second_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='sixth_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='third_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/'),
        ),
    ]
