# Generated by Django 5.0.2 on 2024-03-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_summary_alter_product_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.CharField(blank=True, max_length=145, null=True),
        ),
    ]
