# Generated by Django 5.0.2 on 2024-03-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_female_inventory_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='female_inventory_count',
            new_name='female_inventory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='male_inventory_count',
            new_name='male_inventory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
