# Generated by Django 5.0.2 on 2024-03-16 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_female_inventory_count_product_female_inventory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_video', models.FileField(blank=True, null=True, upload_to='uploads/product_videos/')),
                ('second_video', models.FileField(blank=True, null=True, upload_to='uploads/product_videos/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Videos', to='store.product')),
            ],
        ),
    ]
