# Generated by Django 5.0.2 on 2024-03-17 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='fifth_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='first_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='fourth_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='second_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='sixth_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='third_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
