# Generated by Django 5.0.2 on 2024-03-19 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_productphoto_fifth_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='fifth_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'tif'])]),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='first_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'tif'])]),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='fourth_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'tif'])]),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='second_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'tif'])]),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='sixth_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'tif'])]),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='third_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'tif'])]),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='first_video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/product_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov', 'mkv', 'wmv', 'flv', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='second_video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/product_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov', 'mkv', 'wmv', 'flv', 'webm'])]),
        ),
    ]
